name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install and build your site with Astro
        uses: withastro/action@v2
          # Estas líneas son opcionales, descoméntalas y ajusta según tu proyecto si es necesario
          # path: .
          # node-version: '14' # o la versión que prefieras
          # package-manager: npm ci

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        # No necesitas ajustes específicos aquí a menos que tengas requisitos particulares
